In [1]:
import numpy as np

In [2]:
def recat(pt, origins):
    """categorize a point based on distance from origin of clusters"""
    nclusters = len(origins)
    min_distance = 10000
    y_new = None
    for j in range(nclusters):
        temp = origins[j] - pt.reshape(
            2,
        )
        dist = np.sqrt(np.dot(temp.T, temp))
        if dist < min_distance:
            min_distance = dist
            y_new = j
    return y_new

In [3]:
def recat_vectorized(pts, origins):
    diff = pts[:, np.newaxis, :] - origins
    dists = np.sqrt(np.sum(diff**2, axis=-1))
    return np.argmin(dists, axis=1)

In [4]:
centers = np.array([[-1, 0], [1, 0], [0, 1], [0, -1], [-2, 1], [-2, -1]])
pt1 = np.array([-2, 1.2])
three_pts = np.array([[-2, 1.2], [-2, -0.8], [0, 0.5]])

In [15]:
diffs = three_pts[:, np.newaxis, :] - centers
print(f"diffs = \n{diffs}")
dists = np.sqrt(np.sum(diffs**2, axis=-1))
print(f"dists = \n{dists}")

diffs = 
[[[-1.   1.2]
  [-3.   1.2]
  [-2.   0.2]
  [-2.   2.2]
  [ 0.   0.2]
  [ 0.   2.2]]

 [[-1.  -0.8]
  [-3.  -0.8]
  [-2.  -1.8]
  [-2.   0.2]
  [ 0.  -1.8]
  [ 0.   0.2]]

 [[ 1.   0.5]
  [-1.   0.5]
  [ 0.  -0.5]
  [ 0.   1.5]
  [ 2.  -0.5]
  [ 2.   1.5]]]
dists = 
[[1.56204994 3.23109888 2.00997512 2.97321375 0.2        2.2       ]
 [1.28062485 3.10483494 2.69072481 2.00997512 1.8        0.2       ]
 [1.11803399 1.11803399 0.5        1.5        2.06155281 2.5       ]]


In [11]:
r1 = recat(pt1, centers)
r2 = np.zeros(three_pts.shape[0])
for i in range(len(three_pts)):
    r2[i] = recat(three_pts[i], centers)
print(r1, r2)
r1 = recat_vectorized(pt1.reshape(1, -1), centers)
r2 = recat_vectorized(three_pts, centers)
print(r1, r2)

4 [4. 5. 2.]
[4] [4 5 2]


In [ ]:
def rbf_similarity(A, B, gamma):
    """
    A: (m, d) array
    B: (n, d) array
    gamma: scalar

    Returns:
        S: (m, n) matrix
        where S[i, j] = exp( -gamma * ||A[i] - B[j]||^2 )
    """
    m = A.shape[0]
    n = B.shape[0]
    S = np.zeros((m, n))

    for i in range(m):
        for j in range(n):
            diff = A[i] - B[j]
            dist_sq = np.dot(diff, diff)
            S[i, j] = np.exp(-gamma * dist_sq)

    return S

In [24]:
A = np.array([[0.0, 0.0], [1.0, 0.0]])  # shape (2, 2)

B = np.array([[0.0, 1.0], [1.0, 1.0], [2.0, 0.0]])

gamma = 0.5

result = rbf_similarity(A, B, gamma)
print(result)

[[0.60653066 0.36787944 0.13533528]
 [0.36787944 0.60653066 0.60653066]]


In [32]:
diffs = A[:, np.newaxis, :] - B
dists1 = np.sum(diffs**2, axis=-1)
print(diffs)
print(dists1)
similarity_fn = lambda X: np.exp(-gamma * X)
print(similarity_fn(dists1))

[[[ 0. -1.]
  [-1. -1.]
  [-2.  0.]]

 [[ 1. -1.]
  [ 0. -1.]
  [-1.  0.]]]
[[1. 2. 4.]
 [2. 1. 1.]]
[[0.60653066 0.36787944 0.13533528]
 [0.36787944 0.60653066 0.60653066]]


In [ ]:
def rbf_similarity_vectorized(A, B, gamma):
    """
    A: (m, d) array
    B: (n, d) array
    gamma: scalar

    Returns:
        S: (m, n) matrix
        where S[i, j] = exp( -gamma * ||A[i] - B[j]||^2 )
    """
    diffs = A[:, np.newaxis, :] - B
    dists = np.sum(diffs**2, axis=-1)
    S = np.exp(-gamma * dists)
    return S

[1.         2.71828183]
